baseURL = 'http://newer.systems/'
languageCode = 'en-us'
title = 'Newer Systems'
theme = 'shelltheme'


[Params]
  description = "Tucker Johnson"
  [Params.Terminal]
  scheme = "SolarizedDark"
  userName = "TuckerJ"
  pcName = "newer.systems"
  workDir = "home"
  profile = "bios/short\\ bio.txt"

  ps1Delay = 0 # prompt speed : [userName]@[pcName]:~/$ , [userName]@[pcName]:~/[workDir]$
  stdoutDelay = 0 # stdout speed : [description] , files in Params.Tree
  commandDelay = 20 # command speed : cd [workDir] , cat [profile] , tree ./[folderName]/


  titleDelay = 0 # title speed : "title" in front matter
  contentDelay = 0 # content speed : content in .md file


  description = """### Tucker Johnson, short bio

  Based in Rochester, New York, Tucker Johnson composes
  works for soloists, ensembles, and electronic media.
  Experiences reading, hiking, and amateur botanizing
  can be found intertwined in his work, alongside

  interests in open-source software and teaching."""

  [Params.Tree]
  use = true
  folderName = "content"
  files = [
    ["works", "/list_of_works.md"],
    ["about", "/about.md"],
    #["projects", "/projects.md"],
    #["collaborative work", "/collaborations,md"],
    #["gallery", "/gallery.md"],
    ["Umbel Press (shop)", "/umbel-press.md"],
    ["contact", "/contact.md"]
  ]
