baseURL = 'http://newer.systems/'
languageCode = 'en-us'
title = 'Newer Systems'
theme = 'shelltheme'


[Params]
  description = "Tucker Johnson"
  [Params.Terminal]
  scheme = "SolarizedDark"
  userName = "TuckerJ"
  pcName = "newer.systems"
  workDir = "website"
  profile = "bios/very\\ short\\ bio.txt"
  profile2 = "news/upcomming\\ events.txt"

  ps1Delay = 0 # prompt speed : [userName]@[pcName]:~/$ , [userName]@[pcName]:~/[workDir]$
  stdoutDelay = 0 # stdout speed : [description] , files in Params.Tree
  commandDelay = 20 # command speed : cd [workDir] , cat [profile] , tree ./[folderName]/


  titleDelay = 0 # title speed : "title" in front matter
  contentDelay = 0 # content speed : content in .md file


  description = """### Tucker Johnson, short bio

  Based in Rochester, New York, Tucker Johnson composes works for
  soloists, ensembles, and electronic media. Experiences reading,
  hiking, and amateur botanizing can be found intertwined in his

  work, alongside a passion for open-source software and teaching."""

  description2 = """### upcoming events

  11/10/22 - Ossia New Music: FLUXUS 2 - Ray Wright Room, Rochester NY, 8:30pm
  ---------->[installation with Zoe Markle, Bass]

  11/14/22 - Eastman Audio Research Studio: More Instruments - Hatch Recital Hall, Rochester NY, 7:30pm
  ---------->[I AM COVERED IN STARCH for stereo playback]

  11/17/22 - Composers' Concert II - Hatch Recital Hall, Rochester NY, 7:30pm
  ---------->[Selections from "Fifteen Keyboard Inventions" performed by Zihan Wu]

  """



  [Params.Tree]
  use = true
  folderName = "content"
  files = [
    ["works", "/list_of_works.md"],
    ["about", "/about.md"],
    #["projects", "/projects.md"],
    ["collaborative work", "/collabs.md"],
    ["gallery", "/gallery.md"],
    ["Umbel Press (shop)", "/umbel-press.md"],
    ["contact", "/contact.md"]
  ]
